import { invoke } from '@tauri-apps/api/core';
import type {AiResponse,BranchInfo,CommitFile,CommitInfo,DiffResult,GitCommandOutput,GitStatus,ParsedConflictFile,RemoteInfo,RepositoryInfo,Settings,StashInfo,TagInfo} from '../types/git';
const call=<T>(cmd:string,args:Record<string,unknown>={})=>invoke<T>(cmd,args);
export const gitService={
 openRepository:(path:string)=>call<RepositoryInfo>('open_repository',{path}), validateRepository:(path:string)=>call<boolean>('validate_repository',{path}), listRecentRepositories:()=>call<string[]>('list_recent_repositories'), saveRecentRepository:(path:string)=>call<string[]>('save_recent_repository',{path}), removeRecentRepository:(path:string)=>call<string[]>('remove_recent_repository',{path}),
 getStatus:(repoPath:string)=>call<GitStatus>('get_status',{repoPath}), stageFile:(repoPath:string,filePath:string)=>call<GitCommandOutput>('stage_file',{repoPath,filePath}), unstageFile:(repoPath:string,filePath:string)=>call<GitCommandOutput>('unstage_file',{repoPath,filePath}), stageAll:(repoPath:string)=>call<GitCommandOutput>('stage_all',{repoPath}), unstageAll:(repoPath:string)=>call<GitCommandOutput>('unstage_all',{repoPath}), discardFile:(repoPath:string,filePath:string)=>call<GitCommandOutput>('discard_file',{repoPath,filePath}), deleteUntrackedFile:(repoPath:string,filePath:string)=>call<GitCommandOutput>('delete_untracked_file',{repoPath,filePath}),
 getDiff:(repoPath:string,filePath:string,cached:boolean)=>call<DiffResult>('get_diff',{repoPath,filePath,cached}), getCommitFileDiff:(repoPath:string,commit:string,filePath:string)=>call<DiffResult>('get_commit_file_diff',{repoPath,commit,filePath}), commit:(repoPath:string,message:string,amend:boolean)=>call<GitCommandOutput>('commit',{repoPath,message,amend}), stagedDiff:(repoPath:string)=>call<string>('staged_diff',{repoPath}),
 listBranches:(repoPath:string)=>call<BranchInfo[]>('list_branches',{repoPath}), createBranch:(repoPath:string,name:string,checkout:boolean)=>call<GitCommandOutput>('create_branch',{repoPath,name,checkout}), checkoutBranch:(repoPath:string,name:string)=>call<GitCommandOutput>('checkout_branch',{repoPath,name}), renameBranch:(repoPath:string,oldName:string,newName:string)=>call<GitCommandOutput>('rename_branch',{repoPath,oldName,newName}), deleteBranch:(repoPath:string,name:string,force:boolean)=>call<GitCommandOutput>('delete_branch',{repoPath,name,force}), compareBranch:(repoPath:string,branch:string)=>call<string>('compare_branch',{repoPath,branch}),
 listRemotes:(repoPath:string)=>call<RemoteInfo[]>('list_remotes',{repoPath}), fetch:(repoPath:string,remote='origin')=>call<GitCommandOutput>('fetch',{repoPath,remote}), pull:(repoPath:string)=>call<GitCommandOutput>('pull',{repoPath}), push:(repoPath:string)=>call<GitCommandOutput>('push',{repoPath}), pushNewBranch:(repoPath:string,remote:string,branch:string)=>call<GitCommandOutput>('push_new_branch',{repoPath,remote,branch}),
 getHistory:(repoPath:string,limit=80)=>call<CommitInfo[]>('get_history',{repoPath,limit}), getCommitFiles:(repoPath:string,commit:string)=>call<CommitFile[]>('get_commit_files',{repoPath,commit}), compareCommits:(repoPath:string,from:string,to:string)=>call<string>('compare_commits',{repoPath,from,to}),
 mergeBranch:(repoPath:string,branch:string)=>call<GitCommandOutput>('merge_branch',{repoPath,branch}), abortMerge:(repoPath:string)=>call<GitCommandOutput>('abort_merge',{repoPath}), continueMerge:(repoPath:string)=>call<GitCommandOutput>('continue_merge',{repoPath}), parseConflictFile:(repoPath:string,filePath:string)=>call<ParsedConflictFile>('parse_conflict_file',{repoPath,filePath}), saveResolvedFile:(repoPath:string,filePath:string,content:string)=>call<GitCommandOutput>('save_resolved_file',{repoPath,filePath,content}),
 startRebase:(repoPath:string,onto:string)=>call<GitCommandOutput>('start_rebase',{repoPath,onto}), continueRebase:(repoPath:string)=>call<GitCommandOutput>('continue_rebase',{repoPath}), abortRebase:(repoPath:string)=>call<GitCommandOutput>('abort_rebase',{repoPath}), skipRebase:(repoPath:string)=>call<GitCommandOutput>('skip_rebase',{repoPath}),
 listStashes:(repoPath:string)=>call<StashInfo[]>('list_stashes',{repoPath}), createStash:(repoPath:string,message:string)=>call<GitCommandOutput>('create_stash',{repoPath,message}), applyStash:(repoPath:string,stash:string)=>call<GitCommandOutput>('apply_stash',{repoPath,stash}), popStash:(repoPath:string,stash:string)=>call<GitCommandOutput>('pop_stash',{repoPath,stash}), dropStash:(repoPath:string,stash:string)=>call<GitCommandOutput>('drop_stash',{repoPath,stash}),
 listTags:(repoPath:string)=>call<TagInfo[]>('list_tags',{repoPath}), createLightweightTag:(repoPath:string,name:string)=>call<GitCommandOutput>('create_lightweight_tag',{repoPath,name}), createAnnotatedTag:(repoPath:string,name:string,message:string)=>call<GitCommandOutput>('create_annotated_tag',{repoPath,name,message}), deleteTag:(repoPath:string,name:string)=>call<GitCommandOutput>('delete_tag',{repoPath,name}), pushTag:(repoPath:string,remote:string,name:string)=>call<GitCommandOutput>('push_tag',{repoPath,remote,name}),
 runValidation:(repoPath:string)=>call<GitCommandOutput[]>('run_validation',{repoPath}), explainDiff:(repoPath:string,diff:string,provider:string,model:string)=>call<AiResponse>('explain_diff',{repoPath,diff,provider,model}), generateCommitMessage:(repoPath:string,provider:string,model:string)=>call<AiResponse>('generate_commit_message',{repoPath,provider,model}), suggestBranchName:(description:string,provider:string,model:string)=>call<AiResponse>('suggest_branch_name',{description,provider,model}), resolveConflictBlock:(current:string,incoming:string,provider:string,model:string)=>call<AiResponse>('resolve_conflict_block',{current,incoming,provider,model}), getSettings:()=>call<Settings>('get_settings'), saveSettings:(settings:Settings)=>call<Settings>('save_settings',{settings})
};
