pub mod commands;
pub mod models;
pub mod services;
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            commands::repository::validate_repository,
            commands::repository::open_repository,
            commands::repository::list_recent_repositories,
            commands::repository::save_recent_repository,
            commands::repository::remove_recent_repository,
            commands::status::get_status,
            commands::staging::stage_file,
            commands::staging::unstage_file,
            commands::staging::stage_all,
            commands::staging::unstage_all,
            commands::staging::discard_file,
            commands::staging::delete_untracked_file,
            commands::diff::get_diff,
            commands::diff::get_commit_file_diff,
            commands::commit::commit,
            commands::commit::staged_diff,
            commands::branch::list_branches,
            commands::branch::create_branch,
            commands::branch::checkout_branch,
            commands::branch::rename_branch,
            commands::branch::delete_branch,
            commands::branch::compare_branch,
            commands::remote::list_remotes,
            commands::remote::fetch,
            commands::remote::pull,
            commands::remote::push,
            commands::remote::push_new_branch,
            commands::history::get_history,
            commands::history::get_commit_files,
            commands::history::compare_commits,
            commands::merge::merge_branch,
            commands::merge::abort_merge,
            commands::merge::continue_merge,
            commands::merge::parse_conflict_file,
            commands::merge::save_resolved_file,
            commands::rebase::start_rebase,
            commands::rebase::continue_rebase,
            commands::rebase::abort_rebase,
            commands::rebase::skip_rebase,
            commands::stash::list_stashes,
            commands::stash::create_stash,
            commands::stash::apply_stash,
            commands::stash::pop_stash,
            commands::stash::drop_stash,
            commands::tag::list_tags,
            commands::tag::create_lightweight_tag,
            commands::tag::create_annotated_tag,
            commands::tag::delete_tag,
            commands::tag::push_tag,
            commands::validation::run_validation,
            commands::ai::ai_complete,
            commands::ai::explain_diff,
            commands::ai::generate_commit_message,
            commands::ai::suggest_branch_name,
            commands::ai::resolve_conflict_block,
            commands::settings::get_settings,
            commands::settings::save_settings
        ])
        .run(tauri::generate_context!())
        .expect("failed to run GitPilot");
}
